// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEGAHWJR7ooY8KCOewwahsB7AP_jKTFNk',
    appId: '1:246846174429:web:234f6b4bb3786253dd9734',
    messagingSenderId: '246846174429',
    projectId: 'simple-book-shop',
    authDomain: 'simple-book-shop.firebaseapp.com',
    storageBucket: 'simple-book-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD353UTteU250Xr86RpgoH9nfcIpAj3_C8',
    appId: '1:246846174429:android:4fdb20e9e1118f61dd9734',
    messagingSenderId: '246846174429',
    projectId: 'simple-book-shop',
    storageBucket: 'simple-book-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5vTUYhtwlfMU5hOo6w9IrPu92pfqqlUE',
    appId: '1:246846174429:ios:0efd3b512c20d6eadd9734',
    messagingSenderId: '246846174429',
    projectId: 'simple-book-shop',
    storageBucket: 'simple-book-shop.appspot.com',
    iosBundleId: 'com.example.simpleBookShop',
  );

}